
###
GET http://localhost:8080/fruitParam/?name=orange

###
GET http://localhost:8080/fruitPathShort/orange

###
GET http://localhost:8080/fruitPath/orange

###
GET http://localhost:8080/fruitNoParam/?name=orange
